"""contas, sessoes e locais salvos

A migracao inicial: as tres tabelas da entrega de locais salvos, e nenhuma
outra. O cache da API externa continua em memoria e o conjunto de cidades do
GeoNames continua sendo o arquivo lido no boot — nenhum dos dois tem tabela,
de proposito. Ver ADR 0004.

Gerada por `--autogenerate` a partir de `app/db/schema.py`, onde cada coluna
esta comentada. Tres pontos do schema que o SQL abaixo mostra e vale conhecer:

- `ix_contas_email_minusculo` e um indice **funcional** sobre `lower(email)`.
  E o que torna o e-mail unico sem diferenciar maiusculas no proprio banco, em
  vez de depender de o codigo lembrar de normalizar antes de inserir.
- as duas chaves estrangeiras sao `ON DELETE CASCADE`: apagar uma conta leva
  seus locais salvos e suas sessoes junto, inclusive por SQL direto.
- `uq_local_por_conta` e por `(conta_id, identidade)`, e nao global: duas
  contas podem salvar a mesma cidade.

Revision ID: f9caeb6221c0
Revises: 
Create Date: 2026-09-15 22:22:26.186285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9caeb6221c0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('criada_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_contas_email_minusculo', 'contas', [sa.literal_column('lower(email)')], unique=True)
    op.create_table('locais_salvos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conta_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('admin1', sa.String(length=200), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('identidade', sa.String(length=64), nullable=False),
    sa.Column('salvo_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conta_id'], ['contas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conta_id', 'identidade', name='uq_local_por_conta')
    )
    op.create_index(op.f('ix_locais_salvos_conta_id'), 'locais_salvos', ['conta_id'], unique=False)
    op.create_table('sessoes',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('conta_id', sa.Integer(), nullable=False),
    sa.Column('criada_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expira_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conta_id'], ['contas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessoes_conta_id'), 'sessoes', ['conta_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sessoes_conta_id'), table_name='sessoes')
    op.drop_table('sessoes')
    op.drop_index(op.f('ix_locais_salvos_conta_id'), table_name='locais_salvos')
    op.drop_table('locais_salvos')
    op.drop_index('ix_contas_email_minusculo', table_name='contas')
    op.drop_table('contas')
    # ### end Alembic commands ###
